name: Build Linux Executable

on:
  push:
    branches:
      - linux
    paths:
      - '**/*.cpp'
      - '.github/workflows/linux.yaml'
  workflow_dispatch: {}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Compile C++ Code
      run: |
        g++ -O3 -std=c++17 main.cpp -o program

    - name: Package executable
      run: |
        tar -czf program-linux.tar.gz program

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-program
        path: program-linux.tar.gz
