name: Build Linux Executable

on:
  push:
    branches:
      - linux
    paths:
      - '**/*.cpp'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile C++ Code
      run: |
        g++ -O3 *.cpp -o program

    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: program
