name: Build macOS Executable

on:
  push:
    branches:
      - mac
    paths:
      - '**/*.cpp'
      - '.github/workflows/mac.yaml'
  workflow_dispatch: {}

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C++ Code
      run: |
        clang++ -O3 -std=c++17 main.cpp -o program_mac

    - name: Package executable
      run: |
        tar -czf program-mac.tar.gz program_mac

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-program
        path: program-mac.tar.gz
