name: Build Windows Executable

on:
  push:
    branches:
      - win
    paths:
      - '**/*.cpp'
      - '.github/workflows/win.yaml'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile C++ Code
      run: |
        cl.exe /EHsc /std:c++17 /O2 main.cpp /Fe:program.exe

    - name: Package executable
      run: |
        powershell -Command "Compress-Archive -Path program.exe -DestinationPath program-win.zip"

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-program
        path: program-win.zip
